version: '3'

services:
  todotests:
    image: todotests
    restart: on-failure
    build: ./todo-app/tests
    environment:
      - FRONT_HOST=frontend
    depends_on:
      - todofront
      - todoback

  todofront:
    image: todofrontend
    restart: on-failure
    build: ./todo-app/frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=backend
    depends_on:
      - todoback
  
  todoback:
    image: todobackend
    restart: on-failure
    build: ./todo-app/backend
    ports:
      - 3001:3001
